### ISSUE TITLE
How does gongular prevent race conditions?

### ISSUE THREAD

**Issue by xeoncross** [mustafaakin/gongular#19]
If the same "Handler" struct is populated with values from the request, how does gongular prevent requests from overwriting each other?

**Comment by mustafaakin** [comment]
Each request gets a new instance of handlers.

https://github.com/mustafaakin/gongular/blob/master/handler.go#L226

**Comment by xeoncross** [comment]
Thank you, that makes sense: https://play.golang.org/p/83qyeNdUwkq
