### ISSUE TITLE
dependency injection does not appear to work with interfaces

### ISSUE THREAD

**Issue by blockloop** [mustafaakin/gongular#7]
```
func main() {
    engine := gongular.NewEngine()

    var db store.Store = store.NewStore()
    engine.Provide(db)

    engine.GetRouter().GET("/", &MyHandler{})
    engine.ListenAndServe(":3000")
    // ... rest of code
}

type MyHandler struct {
    DB store.Store // <- an interface
}

func (c *MyHandler) Handle(ctx *gongular.Context) error {
	ctx.SetBody("yay")
	return nil
}
```

With this code I am getting 

> Could not inject type db with key store.Store because No such dependency exists

If I change the property from an interface to the implementation of `store.Store` it works. I also tried with `ProvideWithKey` and it yielded the same results.

The problem is [here](https://github.com/mustafaakin/gongular/blob/a03428141651cd2bddf11df06359084720d45c3c/injector.go#L24). `reflect.TypeOf` will always return the underlying type even if I provide an interface.

**Comment by blockloop** [comment]
Is it possible to inject interface types?

**Comment by blockloop** [comment]
I don't think it's possible to use your current implementation of `Provide` with interfaces. `reflect` will always return the underlying type. I have implemented the following [in my fork](https://github.com/blockloop/gongular/commit/76cefa03aead2ddc6e382b932ad50d1887653ee0) which adds the following signature and it's subsequent layers:

```go
// ProvideUnsafe registers given value by key. Each key can only be registered once and upon injection
// an InjectorError will occur if the property is not assignable from this value
func (inj *injector) ProvideUnsafe(key string, value interface{}) {
	if _, ok := inj.unsafeValues[key]; ok {
		panic(fmt.Sprintf("already provided %#v unsafe value for key %q. ", value, key))
	}

	inj.unsafeValues[key] = reflect.ValueOf(value)
}
```

**Comment by mustafaakin** [comment]
Yes, you are right, I need to provide the interface as is as you did in your fork, If you are to open a PR, I can merge it, thanks! Sorry for the late reply, long weekend!

**Comment by blockloop** [comment]
No worries! I will submit a PR if the changeset is okay with you. I am using the fork on my own project and it works great.

**Comment by mustafaakin** [comment]
Yeah, reflect.TypeOf always returns the underyling type instead of the interface, so we need keys, or we would need to check isAssignable for every type which can be both prone to error and slow, thanks again!
